cc_library(
    name = "gui",
    srcs = [
        "gui.cpp",
    ],
    hdrs = [
        "gui.h",
    ],
    deps = [
        "@dear_imgui//:dear_imgui",
    ],
    visibility = ["//visibility:public"]
)