cc_library(
    name = "price",
    srcs = [
        "coingecko_price.cpp",
        "price_factory.cpp",
        "price.cpp",
    ],
    hdrs = [
        "coingecko_price.h",
        "price_factory.h",
        "price.h",
    ],
    deps = [
        "//http",
        "//json",
    ],
    visibility = ["//visibility:public"]
)